const STORE_LOCATION = {
  name: "Madcenter Construção",
  address: "R. Airton Senna, 77 - Timon/MA",
  city: "Timon",
  state: "MA",
  lat: -4.760287,
  lng: -42.573777
};

const VEHICLE_TYPES = [
  { id: "moto", nome: "Moto", capacidade: 20, custoBase: 10, custoKm: 1.4, uso: "Entregas pequenas e urgentes" },
  { id: "caminhonete", nome: "Caminhonete", capacidade: 500, custoBase: 25, custoKm: 2.8, uso: "Entregas médias" },
  { id: "bau-leve", nome: "Caminhão baú leve", capacidade: 1500, custoBase: 60, custoKm: 4.3, uso: "Entregas protegidas" },
  { id: "tres-quartos", nome: "Caminhão 3/4", capacidade: 3000, custoBase: 95, custoKm: 5.9, uso: "Rotas de maior volume" },
  { id: "carroceria-aberta", nome: "Caminhão carroceria aberta", capacidade: 5000, custoBase: 130, custoKm: 7.0, uso: "Materiais volumosos" }
];

const MUNICIPIOS_COORDS = {
  "timon-ma": { nome: "Timon", estado: "MA", lat: -4.760287, lng: -42.573777 },
  "jose de freitas-pi": { nome: "José de Freitas", estado: "PI", lat: -4.43028, lng: -42.62778 },
  "teresina-pi": { nome: "Teresina", estado: "PI", lat: -5.0892, lng: -42.8016 },
  "caxias-ma": { nome: "Caxias", estado: "MA", lat: -4.8589, lng: -43.3561 },
  "codo-ma": { nome: "Codó", estado: "MA", lat: -4.4556, lng: -43.8924 },
  "campo maior-pi": { nome: "Campo Maior", estado: "PI", lat: -4.8278, lng: -42.1686 },
  "sao luis-ma": { nome: "São Luís", estado: "MA", lat: -2.5307, lng: -44.3068 }
};

const DEFAULT_SETTINGS = {
  empresa: "Madcenter Construção",
  telefone: "(86) 99999-4500",
  endereco: "Av. Principal, 1200 - José de Freitas/PI",
  cidadeBase: STORE_LOCATION.city,
  estado: STORE_LOCATION.state,
  latitudeLoja: STORE_LOCATION.lat,
  longitudeLoja: STORE_LOCATION.lng,
  custoKm: 4.6,
  custoAdicionalFixo: 0,
  freteMinimo: 20,
  entregaMoto: "sim",
  horario: "Segunda a sábado, 7h às 18h",
  tema: "light"
};

const SEED_DATA = {
  cargas: [
    {
      id: "car-001",
      codigo: "PD-1001",
      descricao: "20 latas de tinta acrílica",
      tipo: "Tintas",
      peso: 620,
      volume: "18 volumes",
      destinoMunicipio: "Teresina",
      destinoEstado: "PI",
      enderecoEntrega: "Av. Jóquei Clube, 880",
      cliente: "Fernanda Lima",
      telefone: "(86) 97777-4433",
      coleta: "2026-05-15",
      entrega: "2026-05-15",
      prioridade: "normal",
      veiculoTipo: "bau-leve",
      distanciaKm: 44.4,
      valorFrete: 238,
      status: "em rota",
      observacoes: "Entrega para obra residencial."
    },
    {
      id: "car-002",
      codigo: "PD-1002",
      descricao: "Materiais elétricos e acessórios",
      tipo: "Elétrica",
      peso: 220,
      volume: "8 caixas",
      destinoMunicipio: "Teresina",
      destinoEstado: "PI",
      enderecoEntrega: "Condomínio Solar Leste",
      cliente: "Carlos Andrade",
      telefone: "(86) 98888-1001",
      coleta: "2026-05-15",
      entrega: "2026-05-15",
      prioridade: "alta",
      veiculoTipo: "bau-leve",
      distanciaKm: 44.4,
      valorFrete: 238,
      status: "aguardando rota",
      observacoes: "Pedido agrupável com tintas."
    },
    {
      id: "car-003",
      codigo: "PD-1003",
      descricao: "Kit hidráulico residencial",
      tipo: "Hidráulica",
      peso: 380,
      volume: "12 caixas",
      destinoMunicipio: "Caxias",
      destinoEstado: "MA",
      enderecoEntrega: "Canteiro Vale Verde, BR-316",
      cliente: "Construtora Vale Verde",
      telefone: "(99) 98111-2200",
      coleta: "2026-05-16",
      entrega: "2026-05-16",
      prioridade: "normal",
      veiculoTipo: "caminhonete",
      distanciaKm: 87.2,
      valorFrete: 244,
      status: "aguardando rota",
      observacoes: "Sistema hidráulico completo."
    },
    {
      id: "car-004",
      codigo: "PD-1004",
      descricao: "Ferramentas manuais e EPIs",
      tipo: "Ferramentas",
      peso: 90,
      volume: "5 caixas",
      destinoMunicipio: "Caxias",
      destinoEstado: "MA",
      enderecoEntrega: "Rua 1, lote 22",
      cliente: "Construtora Vale Verde",
      telefone: "(99) 98111-2200",
      coleta: "2026-05-16",
      entrega: "2026-05-16",
      prioridade: "normal",
      veiculoTipo: "caminhonete",
      distanciaKm: 87.2,
      valorFrete: 244,
      status: "aguardando rota",
      observacoes: "Entrega conjunta com hidráulica."
    },
    {
      id: "car-005",
      codigo: "PD-1005",
      descricao: "15 caixas de piso cerâmico",
      tipo: "Pisos e revestimentos",
      peso: 980,
      volume: "15 caixas",
      destinoMunicipio: "Codó",
      destinoEstado: "MA",
      enderecoEntrega: "Residencial Nova Vida, Quadra 4",
      cliente: "Residencial Nova Vida",
      telefone: "(99) 99910-0010",
      coleta: "2026-05-17",
      entrega: "2026-05-17",
      prioridade: "urgente",
      veiculoTipo: "tres-quartos",
      distanciaKm: 154.1,
      valorFrete: 938,
      status: "aguardando rota",
      observacoes: "Carga frágil, exige cuidado."
    },
    {
      id: "car-006",
      codigo: "PD-1006",
      descricao: "Argamassa e rejunte",
      tipo: "Cimento e argamassa",
      peso: 1100,
      volume: "2 pallets",
      destinoMunicipio: "Codó",
      destinoEstado: "MA",
      enderecoEntrega: "Residencial Nova Vida, Quadra 4",
      cliente: "Residencial Nova Vida",
      telefone: "(99) 99910-0010",
      coleta: "2026-05-17",
      entrega: "2026-05-17",
      prioridade: "alta",
      veiculoTipo: "tres-quartos",
      distanciaKm: 154.1,
      valorFrete: 938,
      status: "aguardando rota",
      observacoes: "Parada em Caxias antes do destino."
    },
    {
      id: "car-007",
      codigo: "PD-1007",
      descricao: "Pequena entrega de ferramentas",
      tipo: "Ferramentas",
      peso: 18,
      volume: "1 caixa",
      destinoMunicipio: "Teresina",
      destinoEstado: "PI",
      enderecoEntrega: "Rua das Palmeiras, 430",
      cliente: "Carlos Andrade",
      telefone: "(86) 98888-1001",
      coleta: "2026-05-15",
      entrega: "2026-05-15",
      prioridade: "urgente",
      veiculoTipo: "moto",
      distanciaKm: 44.4,
      valorFrete: 62,
      status: "próximo dia",
      observacoes: "Pequena urgência para entrega rápida."
    }
  ],
  motoristas: [
    { id: "mot-001", nome: "Francisco Moura", telefone: "(86) 99921-4432", categoria: "D", capacidade: 3200, cidade: "Timon", estado: "MA", status: "em entrega", observacoes: "Entregas intermunicipais." },
    { id: "mot-002", nome: "Raimundo Alves", telefone: "(99) 98845-1122", categoria: "D", capacidade: 1800, cidade: "Timon", estado: "MA", status: "disponível", observacoes: "Disponível para rotas de médio porte." },
    { id: "mot-003", nome: "José Pereira", telefone: "(86) 97718-5544", categoria: "E", capacidade: 5000, cidade: "Caxias", estado: "MA", status: "disponível", observacoes: "Experiente em rotas de carga pesada." }
  ],
  rotas: [
    {
      id: "rot-001",
      codigo: "RT-2001",
      nome: "Teresina - Tintas e elétricos",
      tipoRota: "Rodoviária",
      destinoMunicipio: "Teresina",
      destinoEstado: "PI",
      motoristaId: "mot-001",
      cargasIds: ["car-001"],
      saida: "2026-05-15T08:00",
      chegada: "2026-05-15T12:00",
      distancia: 44.4,
      freteTotal: 238,
      tempo: "1h20",
      status: "em andamento",
      observacoes: "Rota em andamento para Teresina."
    }
  ]
};
